---
version: 2
sources:
- name: "ayush_demos.demos"
  database: "ayush_demos"
  schema: "demos"
  tables:
  - name: "my_temp_view"
    columns:
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "event_type"
      dataType:
        type: "String"
    - name: "event_time"
      dataType:
        type: "Timestamp"
    - name: "country"
      dataType:
        type: "String"
    - name: "city"
      dataType:
        type: "String"
    type: "view"
  - name: "initial_table"
    description: "Customer information including status, effective dates, and addresses,\
      \ supporting customer relationship management."
    columns:
    - name: "customer_id"
      description: "Unique identifier for each customer."
      dataType:
        type: "Bigint"
    - name: "customer_name"
      description: "Full name of the customer."
      dataType:
        type: "String"
    - name: "address"
      description: "Residential or business address of the customer."
      dataType:
        type: "String"
    - name: "status"
      description: "Current status of the customer, indicating their active or inactive\
        \ state."
      dataType:
        type: "String"
    - name: "effective_date"
      description: "Date when the customer's current status or record became effective."
      dataType:
        type: "Date"
    - name: "end_date"
      description: "The date when the record or activity is set to conclude."
      dataType:
        type: "Date"
    - name: "extra_col"
      description: "An additional column for storing supplementary information."
      dataType:
        type: "String"
    - name: "dbt_scd_id"
      description: "Unique identifier for the slowly changing dimension record."
      dataType:
        type: "String"
    - name: "dbt_valid_from"
      description: "The start date from which the record is considered valid."
      dataType:
        type: "String"
    - name: "dbt_valid_to"
      description: "The end date until which the record remains valid."
      dataType:
        type: "String"
    - name: "dbt_updated_at"
      description: "Timestamp indicating the last time the record was updated."
      dataType:
        type: "Timestamp"
    type: "table"
  - name: "customer"
    columns:
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "event_type"
      dataType:
        type: "String"
    - name: "event_time"
      dataType:
        type: "Timestamp"
    - name: "country"
      dataType:
        type: "String"
    - name: "city"
      dataType:
        type: "String"
    type: "table"
  - name: "new_table"
    columns:
    - name: "id"
      dataType:
        type: "Integer"
    - name: "age"
      dataType:
        type: "Integer"
    type: "table"
  - name: "newtable"
    columns:
    - name: "id"
      dataType:
        type: "Integer"
    - name: "age"
      dataType:
        type: "Integer"
    type: "table"
  - name: "dummytable"
    columns:
    - name: "id"
      dataType:
        type: "Integer"
    - name: "age"
      dataType:
        type: "Integer"
    type: "table"
